version: '3'

services:
  credit-rating-engine:
    hostname: credit-rating-engine
    container_name: credit-rating-engine
    build: .
    volumes:
      - ./webservice:/webservice
    ports:
      - "5000:5000"
    command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "4", "webservice.wsgi:app"]

